import React, { useEffect, useState } from 'react';
import Head from 'next/head';

import styles from './layouts.module.scss';

import {
  ScrollToTop,
  Footer,
  SocialMediaButtons,
  TopBarLogo,
  TopMenu,
  ResponsiveMenu,
} from '../components';

export const AppLayout = ({ children }) => {
  const [navScrolled, setNavScrolled] = useState(false);
  const [goTopScrolled, setGoTopScrolled] = useState(false);

  useEffect(() => {
    window.addEventListener('scroll', handleScroll, { passive: true });

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  const handleScroll = () => {
    checkNavScroll();
    checkGoTopScroll();
  };

  const checkNavScroll = () => {
    if (window.scrollY > 200) {
      setNavScrolled(true);
    } else {
      setNavScrolled(false);
    }
  };

  const checkGoTopScroll = () => {
    if (window.scrollY > 800) {
      setGoTopScrolled(true);
    } else {
      setGoTopScrolled(false);
    }
  };

  return (
    <>
      <Head>
        <title>El Sofá Rojo Boudoir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head>

      <nav className={`${styles.nav} ${navScrolled ? styles.navScrolled : ''}`} >
        {/* Topbar Logo */}
        <TopBarLogo navScrolled={navScrolled} styles={styles} />

        {/* Top Menu */}
        <TopMenu styles={styles} />

        {/* Responsive Menu */}
        <ResponsiveMenu navScrolled={navScrolled} styles={styles} />
      </nav>

      {/* Sidebar Social Media Icons */}
      <SocialMediaButtons navScrolled={navScrolled} styles={styles} />

      <div className={styles.globalContainer}>
        {/* Contents */}
        <main className={styles.main}>
          {children}
        </main>

        {/* Go Top Button */}
        <ScrollToTop goTopScrolled={goTopScrolled} styles={styles} />

        {/* Footer */}
        <Footer />
      </div>
    </>
  );
};
