import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import { useRouter } from 'next/router';

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFacebookF, faInstagram, faTwitter } from "@fortawesome/free-brands-svg-icons";

import {
  faBars,
} from "@fortawesome/free-solid-svg-icons";

import { Footer } from '../components/footer/Footer';
import styles from './layouts.module.scss';

import imageLogo from '../assets/images/logo.png';
import imageLogoBlack from '../assets/images/logo_black.png';

export const AppLayout = ({ children }) => {
  const { pathname } = useRouter();
  const [navScrolled, setNavScrolled] = useState(0);

  const handleScroll = () => {
    if (window.scrollY > 200) {
      setNavScrolled(true);
    } else {
      setNavScrolled(false);
    }
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll, { passive: true });

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>El Sofá Rojo Boudoir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head>

      <nav className={`${styles.nav} ${navScrolled ? styles.navScrolled : ''}`} >

        <div className={`${styles.logo} ${navScrolled ? styles.logoScrolled : ''}`}>
          {
            navScrolled
              ? <Image src={imageLogoBlack} />
              : <Image src={imageLogo} />
          }
        </div>

        <div className={styles.menu}>
          {/* Top Menu */}
          <Link href='/'>
            <a className={`${styles.links} ${pathname === '/' ? styles.active : ''}`}>Home</a>
          </Link>

          <Link href='/photoshoots'>
            <a className={`${styles.links} ${pathname.startsWith('/photoshoots') ? styles.active : ''}`}>Galería</a>
          </Link>

          <Link href='/about'>
            <a className={`${styles.links} ${pathname.startsWith('/about') ? styles.active : ''}`}>Sobre nosotros</a>
          </Link>

          <Link href='/blog'>
            <a className={`${styles.links} ${pathname.startsWith('/blog') ? styles.active : ''}`}>Blog</a>
          </Link>

          <Link href='/contact'>
            <a className={`${styles.links} ${pathname.startsWith('/contact') ? styles.active : ''}`}>Contacto</a>
          </Link>
        </div>

        {/* Responsive Menu */}
        <div className={styles.responsiveMenu}>
          <FontAwesomeIcon
            onClick={() => { console.log('click') }}
            className={`${styles.burger} ${navScrolled ? styles.burgerScrolled : ''}`}
            icon={faBars}
          />
        </div>
      </nav>

      {/* Sidebar Social Media Icons */}
      <div className={styles.socialMedia}>
        <FontAwesomeIcon
          onClick={() => window.open('https://www.facebook.com/elsofarojoboudoir/', '_blank')}
          className={`${styles.socialButton} ${styles.facebook} ${navScrolled ? styles.facebookScrolled : ''}`}
          icon={faFacebookF}
        />
        <FontAwesomeIcon
          onClick={() => window.open('https://www.facebook.com/elsofarojoboudoir/', '_blank')}
          className={`${styles.socialButton} ${styles.instagram} ${navScrolled ? styles.instagramScrolled : ''}`}
          icon={faInstagram}
        />
        <FontAwesomeIcon
          onClick={() => window.open('https://www.facebook.com/elsofarojoboudoir/', '_blank')}
          className={`${styles.socialButton} ${styles.twitter} ${navScrolled ? styles.twitterScrolled : ''}`}
          icon={faTwitter}
        />
      </div>

      <div className={styles.globalContainer}>

        <main className={styles.main}>
          {children}
        </main>

        <Footer />
      </div>
    </>
  );
};
