import Head from 'next/head';
import Image from 'next/image';
import { AppLayout } from '../../layouts/AppLayout';

export default function About() {
  return (
    <>
      <Head>
        <title>El Sofá Rojo Boudoir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>
        <h1>Sobre nosotros</h1>

      </AppLayout>
    </>
  )
};